#!/bin/bash

JAR_FILE=JDownloader.jar
MAIN_JAR=$SNAP_USER_COMMON/$JAR_FILE

if [ ! -f $MAIN_JAR ]
then
    cp -f $SNAP/$JAR_FILE $MAIN_JAR
fi

# java
export JAVA_HOME=$SNAP/usr/lib/jvm/java-1.11.0-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

java -jar $MAIN_JAR
